#!/bin/bash
#Needs experimental features enabled and qemu support / a builder set up with arm included!
# linux/arm64/v8 currently disabled as there are some issues on my build system
docker buildx build --progress plain --platform linux/amd64 --no-cache -t mynttt/updatetool:latest -f updatetool-docker/Dockerfile . --push
