#!/bin/bash
# Preconditions: https://netfuture.ch/2020/05/multi-arch-docker-image-easy/
docker buildx build --progress plain --platform linux/arm/v7,linux/386 --builder docker-multiarch --no-cache -t mynttt/updatetool:32bit -f updatetool-docker-32bit/Dockerfile . --push
