#!/bin/bash
# Preconditions: https://netfuture.ch/2020/05/multi-arch-docker-image-easy/
docker buildx build --progress plain --platform linux/amd64,linux/arm64/v8 --builder docker-multiarch --no-cache -t mynttt/updatetool:latest -f updatetool-docker/Dockerfile . --push