#!/bin/bash
# https://github.com/docker/buildx/issues/57

sudo apt-get update && sudo apt-get install -y qemu-user
docker buildx create --platform linux/amd64,linux/arm64 --name updatetoolbuilder
docker buildx use updatetoolbuilder
docker buildx inspect --bootstrap